[package]
org = "wso2"
name = "orders_parser"
version = "0.1.0"
distribution = "2201.12.0"
title = "orders-parser"

[build-options]
sticky = true

[[dependency]]
org="ballerina"
name="edi"
version="1.6.0"
