[package]
org = "ballerina"
name = "edi"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["edi"]
repository = "https://github.com/ballerina-platform/module-ballerina-edi"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.12.0-20250226-081700-17d84e0f"
