[package]
org = "ballerina"
name = "edi"
version = "1.5.4"
authors = ["Ballerina"]
keywords = ["edi"]
repository = "https://github.com/ballerina-platform/module-ballerina-edi"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.14.0-20260527-050400-74f7e6bf"
